baseURL = 'https://bamgoesn.github.io/'
languageCode = 'ko'
title = '아와와와왕'
theme = "tailwind"

[params]
contentTypeName = "posts"
showReadingTime = false
toc = false

[params.header]
logo = "logo.png"

[params.footer]
since = 2021
poweredby = true

[params.giscus]
enabled = true
repo = "BamgoeSN/BamgoeSN.github.io"
repoID = "MDEwOlJlcG9zaXRvcnkzODU4NzM1NTc="
category = "Announcements"
categoryID = "DIC_kwDOFv_2lc4CcR95"
mapping = "og:title"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
lang = "ko"

[[params.social_media.items]]
enabled = true
title = 'Github'
icon = 'brand-github'
link = 'https://github.com/BamgoeSN'


[menu]

[[menu.main]]
identifier = "post"
name = "Post"
pageRef = "/posts"
weight = 0

[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 10
