baseURL = 'https://bamgoesn.github.io/'
languageCode = 'ko'
title = '아와와와왕'
theme = "tailwind"

[params]
contentTypeName = "posts"
showReadingTime = false
toc = false

[params.header]
logo = "logo.png"

[params.footer]
since = 2021
poweredby = true

[[params.social_media.items]]
enabled = true
title = 'Github'
icon = 'brand-github'
link = 'https://github.com/BamgoeSN'


[menu]

[[menu.main]]
identifier = "post"
name = "Post"
pageRef = "/posts"
weight = 0

[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 10
